### ISSUE TITLE
Cannot open RON file Clion 2019.3.2 IDE fatal error

### ISSUE THREAD

**Issue by reesmanp** [vultix/intellij-ron-plugin#6]
As of Clion version 2019.3.2 I get and IDE fatal error when trying to open a RON file: java.lang.NoSuchFieldException: INSTANCE

```
com.intellij.diagnostic.PluginException: INSTANCE [Plugin: com.vultix.intellij-ron]
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:486)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.findFileTypeByLanguage(FileTypeManagerImpl.java:1209)
	at com.intellij.lang.Language.getAssociatedFileType(Language.java:173)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettings.<init>(CommonCodeStyleSettings.java:67)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.getDefaultCommonSettings(LanguageCodeStyleSettingsProvider.java:108)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.lambda$safelyGetDefaults$0(CommonCodeStyleSettingsManager.java:185)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.safelyGetDefaults(CommonCodeStyleSettingsManager.java:185)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.initNonReadSettings(CommonCodeStyleSettingsManager.java:106)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.getCommonSettingsMap(CommonCodeStyleSettingsManager.java:75)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.getCommonSettings(CommonCodeStyleSettingsManager.java:53)
	at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptions(CodeStyleSettings.java:977)
	at com.intellij.psi.codeStyle.CodeStyleSettings.getLanguageIndentOptions(CodeStyleSettings.java:960)
	at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptions(CodeStyleSettings.java:840)
	at com.jetbrains.cidr.lang.settings.OCCodeStyleSettings.<init>(OCCodeStyleSettings.java:59)
	at com.jetbrains.cidr.lang.settings.OCCodeStyleSettingsProvider.createCustomSettings(OCCodeStyleSettingsProvider.java:18)
	at com.intellij.psi.codeStyle.CodeStyleSettings.<init>(CodeStyleSettings.java:91)
	at com.intellij.psi.codeStyle.CodeStyleSettings.<init>(CodeStyleSettings.java:82)
	at com.intellij.psi.codeStyle.CodeStyleSettings.writeExternal(CodeStyleSettings.java:781)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.writeScheme(CodeStyleSchemeImpl.java:123)
	at com.intellij.configurationStore.LazySchemeProcessor.writeScheme(scheme-impl.kt:63)
	at com.intellij.configurationStore.LazySchemeProcessor.writeScheme(scheme-impl.kt:54)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.saveScheme(SchemeManagerImpl.kt:373)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.save(SchemeManagerImpl.kt:313)
	at com.intellij.configurationStore.schemeManager.SchemeManagerFactoryBase.save(SchemeManagerFactoryImpl.kt:96)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents$saveSettingsSavingComponentsAndCommitComponents$2$1.invokeSuspend(ComponentStoreWithExtraComponents.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at com.intellij.configurationStore.EdtPoolDispatcherManager.processQueue(EdtPoolDispatcher.kt:54)
	at com.intellij.configurationStore.EdtPoolDispatcherManager.access$processQueue(EdtPoolDispatcher.kt:18)
	at com.intellij.configurationStore.EdtPoolDispatcherManager$scheduleFlush$1.invoke(EdtPoolDispatcher.kt:32)
	at com.intellij.configurationStore.EdtPoolDispatcherManager$scheduleFlush$1.invoke(EdtPoolDispatcher.kt:18)
	at com.intellij.configurationStore.EdtPoolDispatcherKt$sam$java_lang_Runnable$0.run(EdtPoolDispatcher.kt)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoSuchFieldException: INSTANCE
	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:476)
	... 55 more
```

**Comment by AidaPaul** [comment]
Same, doesn't work in any recentish versions at all. Is this abandoned?

**Comment by linevych** [comment]
@vultix do you abandoned the project if so maybe it would be a good idea to release the source code?
