### ISSUE TITLE
Plugin does not work with IntelliJ 2020.1

### ISSUE THREAD

**Issue by minecrawler** [vultix/intellij-ron-plugin#8]
This plugin caused my IDE to not open the settings menu and not display TypeScript files after the update anymore. I had to manually delete it from the filesystem.

```
2020-04-10 15:44:44,955 [  46468]  ERROR - rains.concurrency.AsyncPromise - IntelliJ IDEA 2020.1  Build #IU-201.6668.121 
2020-04-10 15:44:44,956 [  46469]  ERROR - rains.concurrency.AsyncPromise - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-04-10 15:44:44,956 [  46469]  ERROR - rains.concurrency.AsyncPromise - OS: Windows 10 
2020-04-10 15:44:44,957 [  46470]  ERROR - rains.concurrency.AsyncPromise - Last Action:  
2020-04-10 15:44:54,820 [  56333]  ERROR - Types.impl.FileTypeManagerImpl - INSTANCE [Plugin: com.vultix.intellij-ron] 
com.intellij.diagnostic.PluginException: INSTANCE [Plugin: com.vultix.intellij-ron]
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:490)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.mergeOrInstantiateFileTypeBean(FileTypeManagerImpl.java:469)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:457)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getRegisteredFileTypes(FileTypeManagerImpl.java:1187)
	at com.intellij.lang.javascript.index.JavaScriptIndex.lambda$static$0(JavaScriptIndex.java:139)
	at com.intellij.openapi.util.ClearableLazyValue$2.compute(ClearableLazyValue.java:30)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:45)
	at com.intellij.openapi.util.AtomicClearableLazyValue.getValue(AtomicClearableLazyValue.java:21)
	at com.intellij.lang.javascript.index.JavaScriptIndex.getFileTypesToIndexJS(JavaScriptIndex.java:133)
	at com.intellij.lang.javascript.index.JavaScriptIndex$1.acceptInput(JavaScriptIndex.java:62)
	at com.intellij.lang.javascript.types.JSFileElementType.shouldBuildStubFor(JSFileElementType.java:57)
	at com.intellij.psi.PsiAnchor.canHaveStub(PsiAnchor.java:145)
	at com.intellij.psi.PsiAnchor.createStubReference(PsiAnchor.java:126)
	at com.intellij.psi.PsiAnchor.doCreateAnchor(PsiAnchor.java:80)
	at com.intellij.psi.PsiAnchor.create(PsiAnchor.java:51)
	at com.intellij.xml.breadcrumbs.PsiCrumb.<init>(PsiCrumb.java:26)
	at com.intellij.xml.breadcrumbs.PsiFileBreadcrumbsCollector.computeCrumbs(PsiFileBreadcrumbsCollector.java:109)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.computeCrumbs(BreadcrumbsXmlWrapper.java:41)
	at com.intellij.xml.breadcrumbs.BreadcrumbsPanel.lambda$updateCrumbs$1(BreadcrumbsPanel.java:182)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:485)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$2(NonBlockingReadActionImpl.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:450)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$0(NonBlockingReadActionImpl.java:383)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchFieldException: INSTANCE
	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:480)
	... 39 more
2020-04-10 15:44:54,821 [  56334]  ERROR - Types.impl.FileTypeManagerImpl - IntelliJ IDEA 2020.1  Build #IU-201.6668.121 
2020-04-10 15:44:54,821 [  56334]  ERROR - Types.impl.FileTypeManagerImpl - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-04-10 15:44:54,822 [  56335]  ERROR - Types.impl.FileTypeManagerImpl - OS: Windows 10 
2020-04-10 15:44:54,822 [  56335]  ERROR - Types.impl.FileTypeManagerImpl - Plugin to blame: RON (Rusty Object Notation) version: 2019.02.01 
2020-04-10 15:44:54,822 [  56335]  ERROR - Types.impl.FileTypeManagerImpl - Last Action:  
2020-04-10 15:44:54,823 [  56336]  ERROR - rains.concurrency.AsyncPromise - @NotNull method com/intellij/openapi/fileTypes/impl/FileTypeManagerImpl.mergeOrInstantiateFileTypeBean must not return null 
java.lang.IllegalStateException: @NotNull method com/intellij/openapi/fileTypes/impl/FileTypeManagerImpl.mergeOrInstantiateFileTypeBean must not return null
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.$$$reportNull$$$0(FileTypeManagerImpl.java)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.mergeOrInstantiateFileTypeBean(FileTypeManagerImpl.java:469)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:457)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getRegisteredFileTypes(FileTypeManagerImpl.java:1187)
	at com.intellij.lang.javascript.index.JavaScriptIndex.lambda$static$0(JavaScriptIndex.java:139)
	at com.intellij.openapi.util.ClearableLazyValue$2.compute(ClearableLazyValue.java:30)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:45)
	at com.intellij.openapi.util.AtomicClearableLazyValue.getValue(AtomicClearableLazyValue.java:21)
	at com.intellij.lang.javascript.index.JavaScriptIndex.getFileTypesToIndexJS(JavaScriptIndex.java:133)
	at com.intellij.lang.javascript.index.JavaScriptIndex$1.acceptInput(JavaScriptIndex.java:62)
	at com.intellij.lang.javascript.types.JSFileElementType.shouldBuildStubFor(JSFileElementType.java:57)
	at com.intellij.psi.PsiAnchor.canHaveStub(PsiAnchor.java:145)
	at com.intellij.psi.PsiAnchor.createStubReference(PsiAnchor.java:126)
	at com.intellij.psi.PsiAnchor.doCreateAnchor(PsiAnchor.java:80)
	at com.intellij.psi.PsiAnchor.create(PsiAnchor.java:51)
	at com.intellij.xml.breadcrumbs.PsiCrumb.<init>(PsiCrumb.java:26)
	at com.intellij.xml.breadcrumbs.PsiFileBreadcrumbsCollector.computeCrumbs(PsiFileBreadcrumbsCollector.java:109)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.computeCrumbs(BreadcrumbsXmlWrapper.java:41)
	at com.intellij.xml.breadcrumbs.BreadcrumbsPanel.lambda$updateCrumbs$1(BreadcrumbsPanel.java:182)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:485)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$2(NonBlockingReadActionImpl.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:450)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$0(NonBlockingReadActionImpl.java:383)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gptshubham595** [comment]
any solution for this?
